<?xml version="1.0"?>
<ArrayOfMessage>
    <Message>
        <Recepients>
            <string>Mace Windu</string>
            <string>Yoda</string>
        </Recepients>
        <Body/>
        <IsIncoming>true</IsIncoming>
        <IsRead>true</IsRead>
        <Attachments>
            <MessageAttachment>
                <AttachmentContentType>text/plain</AttachmentContentType>
                <AttachmentDataBase64String>VwBoAGEAdAAgAGEAYgBvAHUAdAAgAHQAaABlACAAZAByAG8AaQBkACAAYQB0AHQAYQBjAGsAIABvAG4AIAB0AGgAZQAgAFcAbwBvAGsAaQBlAGUAcwA/AA==</AttachmentDataBase64String>
            </MessageAttachment>
        </Attachments>
        <LocalTimestamp>127610067000000000</LocalTimestamp>
        <Sender>Ki-Adi-Mundi</Sender>
    </Message>
    <Message>
        <Recepients>
            <string>Ki-Adi-Mundi</string>
            <string>Yoda</string>
        </Recepients>
        <Body/>
        <IsIncoming>true</IsIncoming>
        <IsRead>true</IsRead>
        <Attachments>
            <MessageAttachment>
                <AttachmentContentType>text/plain</AttachmentContentType>
                <AttachmentDataBase64String>SQB0ACAAaQBzACAAYwByAGkAdABpAGMAYQBsACAAdwBlACAAcwBlAG4AZAAgAGEAbgAgAGEAdAB0AGEAYwBrACAAZwByAG8AdQBwACAAdABoAGUAcgBlACwAIABpAG0AbQBlAGQAaQBhAHQAZQBsAHkAIQA=</AttachmentDataBase64String>
            </MessageAttachment>
        </Attachments>
        <LocalTimestamp>127610070190000000</LocalTimestamp>
        <Sender>Mace Windu</Sender>
    </Message>
    <Message>
        <Recepients>
            <string>Ki-Adi-Mundi</string>
            <string>Mace Windu</string>
            <string>Yoda</string>
        </Recepients>
        <Body/>
        <IsIncoming>false</IsIncoming>
        <IsRead>true</IsRead>
        <Attachments>
            <MessageAttachment>
                <AttachmentContentType>text/plain</AttachmentContentType>
                <AttachmentDataBase64String>SABlACcAcwAgAHIAaQBnAGgAdAAsACAAdABoAGEAdAAgAGkAcwAgAGEAIABzAHkAcwB0AGUAbQAgAHcAZQAgAGMAYQBuAG4AbwB0ACAAYQBmAGYAbwByAGQAIAB0AG8AIABsAG8AcwBlAC4A</AttachmentDataBase64String>
            </MessageAttachment>
        </Attachments>
        <LocalTimestamp>127610073380000000</LocalTimestamp>
        <Sender/>
    </Message>
    <Message>
        <Recepients>
            <string>Ki-Adi-Mundi</string>
            <string>Mace Windu</string>
            <string>Yoda</string>
        </Recepients>
        <Body/>
        <IsIncoming>false</IsIncoming>
        <IsRead>true</IsRead>
        <Attachments>
            <MessageAttachment>
                <AttachmentContentType>text/plain</AttachmentContentType>
                <AttachmentDataBase64String>SQB0ACcAcwAgAHQAaABlACAAbQBhAGkAbgAgAG4AYQB2AGkAZwBhAHQAaQBvAG4AIAByAG8AdQB0AGUAIABmAG8AcgAgAHQAaABlACAAcwBvAHUAdABoAHcAZQBzAHQAZQByAG4AIABxAHUAYQBkAHIAYQBuAHQALgA=</AttachmentDataBase64String>
            </MessageAttachment>
        </Attachments>
        <LocalTimestamp>127610073680000000</LocalTimestamp>
        <Sender/>
    </Message>
    <Message>
        <Recepients>
            <string>General Grievous</string>
        </Recepients>
        <Body>Hello there.</Body>
        <IsIncoming>false</IsIncoming>
        <IsRead>true</IsRead>
        <Attachments/>
        <LocalTimestamp>127610118300000000</LocalTimestamp>
        <Sender/>
    </Message>
    <Message>
        <Recepients/>
        <Body>General Kenobi. You are a bold one.</Body>
        <IsIncoming>true</IsIncoming>
        <IsRead>true</IsRead>
        <Attachments/>
        <LocalTimestamp>127610118620000000</LocalTimestamp>
        <Sender>General Grievous</Sender>
    </Message>
</ArrayOfMessage>
