name: GitHub Actions CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python3 -m pip install --requirement requirements.txt
          fi
          python3 -m pip install pylint
      - name: Analyzing Python files with pylint
        run: python3 -m pylint src test text_me
      - name: Run unit tests
        run: python3 -m unittest
